### ImpactOfDataVolumeService methods
### Get appointment100000 and patient10000
GET http://localhost:8086/api/data-volume/appointment100000-and-patient10000?hkidPrefix=A%25

### Get appointment5000000 and patient2000000
GET http://localhost:8086/api/data-volume/appointment5000000-and-patient2000000?hkidPrefix=A%25

### Get appointment50000000 and patient10000000
GET http://localhost:8086/api/data-volume/appointment50000000-and-patient10000000?hkidPrefix=A%25

### ImpactOfResultSetSizeService methods
### Get result set size 50
GET http://localhost:8086/api/result-set-size/50?hkidPrefix=A%25

### Get result set size 1000
GET http://localhost:8086/api/result-set-size/1000?hkidPrefix=A%25

### Get result set size 10000
GET http://localhost:8086/api/result-set-size/10000?hkidPrefix=A%25

### ImpactOfTypeOfJoinAndSubqueryService methods
### Get type of join
GET http://localhost:8086/api/type-of-join?hkidPrefix=A%25

### Get type of left join
GET http://localhost:8086/api/type-of-left-join?hkidPrefix=A%25

### Get type of subquery
GET http://localhost:8086/api/type-of-subquery?hkidPrefix=A%25

### ImpactOfDatabaseInstanceInvolvedService methods
### Get two database instance involved
GET http://localhost:8086/api/database-instance-involved/two?hkidPrefix=A%25

### Get three database instance involved
GET http://localhost:8086/api/database-instance-involved/three?hkidPrefix=A%25

### Get four database instance involved
GET http://localhost:8086/api/database-instance-involved/four?hkidPrefix=A%25
